Camera shutter effect and thumbnails
inaturalist/iNaturalistReactNative pull request #133
Opened 2022-08-01 19:44 UTC by albullington

- Adds a thumbnail and loading wheel to camera preview when a user presses the shutter button
- Creates an animated view overlaying the camera, which fades in and out on shutter press

2022-08-02 20:53 UTC, kueda requested changes
Haven't done a full read of this yet, but the first issue that occurs to me is that the camera doesn't fade back in until after the preview icon finishes loading. Can we separate those two processes? IMO, the camera view should just fade in and out very quickly, enough to provide an immediate response to the user's tap on the shutter. The preview generation can take as long as it needs to take, but it shouldn't hold up the process of taking more photos.

2022-08-02 23:33 UTC, albullington commented
The camera animation and the preview icon should be unrelated processes. Right now, the camera animation is being triggered by the shutter press. The fade out lasts for a certain duration in milliseconds, then when the fade out is complete, the fade back in is triggered for the same duration. I tried changing the duration to 5 milliseconds to see if that feels more like the duration you're expecting.

2022-08-03 17:55 UTC, albullington commented
I *think* this should be working better now.

2022-08-05 01:31 UTC, kueda requested changes
Mostly looking good, and thanks for all the back-and-forth about the shutter duration. These remaining requests are all pretty minor.

2022-08-05 01:31 UTC, kueda commented on src/components/Camera/FadeInOutView.js
> +  const heightPhotoContainerCamera = 134;
Does this need to be hard-coded? It seems to get repeated [here](https://github.com/inaturalist/iNaturalistReactNative/pull/133/files#diff-ecca3df0533d935137cea989efddaefb2f009aeca3b7f14c8ffd4cf7ca1216ceR85) so maybe it should be extracted, or be some kind of constant in the style.

2022-08-05 01:31 UTC, kueda commented on src/components/Camera/PhotoPreview.js
> +        bottom: 16 + insets.top
Kind of the same thing here. You could just allow the style to set this value once with `bottom: textStyles.topPhotoText.bottom + insets.top`

2022-08-05 01:31 UTC, kueda commented on src/components/Camera/PhotoPreview.js
> +          // contentContainerStyle={viewStyles.container}
Please delete this comment and maybe `viewStyles.container` unless we're actually going to use it.

2022-08-05 01:31 UTC, kueda commented on src/components/MediaViewer/MediaViewer.js
> +// import ViewNoFooter from "../SharedComponents/ViewNoFooter";
Another comment to remove.

2022-08-05 01:31 UTC, kueda commented on src/components/MediaViewer/MediaViewer.js
>  const selectedImageHeight = height - 350;
I know this isn't a part of this PR, but this is another literal that could probably be calculated from styles or made a constant or something. Usually when I see something like this I think, "Why 350? What's this going to look like on a tablet?"

2022-08-05 16:53 UTC, merged