Add swipe to media viewer
inaturalist/iNaturalistReactNative pull request #136
Opened 2022-08-01 23:11 UTC by albullington

- Lets a user swipe between photos in the bottom carousel when the main photo is zoomed out
- Fixes some styling issues; makes the media viewer full screen on iPhone X devices

2022-08-05 01:50 UTC, kueda requested changes
No problem with the code here but I'm pretty sure this is not the kind of swipe we're shooting for. I was thinking something more along the lines of https://www.npmjs.com/package/react-native-swiper, where you can see both the current photo and the one you're swiping to at the same time.

2022-08-10 22:37 UTC, albullington commented
@kueda I still have some work to do related to tapping a photo in the carousel, having the FlatList scroll to the correct spot, & updating the green selection box around the photo in the carousel (like, making this less jittery). But otherwise, does this look more like the type of swiper you were originally thinking of? Is there anything else we would need to do to make this work more like `react-native-swiper`? Want to make sure this is at least on the right track.

2022-08-10 23:37 UTC, kueda reviewed
Totally on track in terms of functionality! I like.

2022-08-11 18:33 UTC, albullington commented
Ok, ready for re-review.

2022-08-13 00:16 UTC, kueda requested changes
This is looking really good. The only blocker is that fake-out scroll bug where the carousel and the flat list get out of sync.

2022-08-13 00:16 UTC, kueda commented on src/components/MediaViewer/HorizontalScroll.js
> +        onScrollEndDrag={handleScrollEndDrag}
This approach is causing this bug: if you touch down, slide to the next image but don't release, then slide back to the original image, then release, this even seems to fire before the glide animation finishes, which means the `PhotoCarousel` highlights the next image while the `FlatList` is still showing the first.

I can sort of address this by using [`onMomentumScrollEnd`](https://reactnative.dev/docs/scrollview#onmomentumscrollend) instead ([thanks, SO](https://stackoverflow.com/questions/43370807/react-native-get-current-page-in-flatlist-when-using-pagingenabled)), but that seems to call the callback multiple times which causes jitter, and I'm not sure how to tell which event is the last without doing something unpleasant like `setTimeout`. Any ideas?

2022-08-13 00:16 UTC, kueda commented on src/components/MediaViewer/CustomImageZoom.js
> +      onStartShouldSetPanResponder={onPanResponder}
I'm nitpicking here, but I don't think there's a reason to define a method for this (unless there's some kind of performance savings?), and I might re-write it for readability like this:

```
onStartShouldSetPanResponder={e => {
  const pinching = e.nativeEvent.touches.length === 2;
  const alreadyZooming = scaleValue.current > 1;
  return pinching || alreadyZooming;
}}
```

2022-08-16 21:46 UTC, albullington commented
I think this should be looking better now -- changed the way `handleScrollEndDrag` determines which index to select next for the photo carousel.

2022-08-17 23:10 UTC, kueda requested changes
Blocking:
- [ ] The back button in the media viewer should look the same in iOS and Android, right? It should at least not be dark gray in Android, which makes it almost invisible

Not blocking:
- [ ] If there are more photos than will fit in the PhotoPreview and you tap on the last one, there's no indication that there are more photos; you just have to try swiping. One way to address this would be size the photo previews so the last one is always half off-screen, but we should probably consult with Abhas

2022-08-18 18:12 UTC, merged