Refactored location fetching for accurate locations
inaturalist/iNaturalistReactNative pull request #1788
Opened 2024-07-10 00:08 UTC by albullington

Closes #1688

- Location fetching uses watchPosition, as suggested in https://github.com/inaturalist/iNaturalistReactNative/issues/1744
- Exposes `userLocation` for scenarios where we want a location value that's not attached to an observation, like ProjectContainer (replacing the `useUserLocation` hook). Otherwise, updates observation keys with the new location
- Stops watch when an accurate enough location is found

Note: I resisted the urge to refactor `useWatchPosition` out of the Camera and into Suggestions, since that should be addressed in part by the changes to permissions issue: https://github.com/inaturalist/iNaturalistReactNative/issues/1594. Right now, I think having `useWatchPosition` in the Camera slows down performance a tiny bit, but we need permission changes and a permission gate (https://github.com/inaturalist/iNaturalistReactNative/issues/1755) for user location fetching on the Suggestions screen

A few things to think about when reviewing:

1. Does this impact performance, since this hook is called multiple times? (My sense is yes for the current Camera screen which we'll refactor into Suggestions soon, and no for other flows)
2. Are locations accurate when walking to different locations online/offline? Are there any moments when they're not updating?
3. Are gallery photos still using the correct evidence-location? Are there scenarios when this is being overwritten by the watch position hook? (It seemed like this was happening for me out in the field, but not at home...)
4. Do we need a timeout so the loading wheel doesn't show forever on ObsEdit?

2024-07-10 21:40 UTC, kueda requested changes
Doesn't work on my iPhone SE.

1. Fresh install
1. Change to advanced mode
1. Add an obs w/o evidence
1. Immediately get this infinite recursion leading to a freeze:
    ```
    ERROR  Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
       in PermissionGateContainer (created by LocationPermissionGate)
       in LocationPermissionGate (created by EvidenceSection)
       in RCTView (created by View)
       in View
       in NativeWind.View
       in NativeWind.NoName
       in Unknown (created by EvidenceSection)
       in EvidenceSection (created by EvidenceSectionContainer)
   ```

I get the same problem when starting with a camera and granting all permissions, except it locks up on Suggestions, even if I run from 3f823d0e33dbc5e0ad759ee2852872d1b212c2b0 (i.e. w/o the typescript changes).

2024-07-10 21:40 UTC, kueda commented on src/sharedHooks/useWatchPosition.ts
> +  const updateObservationKeys = useStore( state => state.updateObservationKeys );
I strongly advise removing this and any observation-specific logic from this hook. It's called watchPosition, so it should just watch the position. If consumers of this module need to do other stuff, they should pass in callbacks as arguments.

In general, you want code to be modular (i.e. reusable) and encapsulated (with as few external dependencies as possible).  There are all kinds of reasons we might want to watch the user's location, so we don't want to tie this functionality to one specific use case.

2024-07-10 21:40 UTC, kueda commented on src/sharedHooks/useWatchPosition.ts
> +      setLocationPermissionResult( "granted" );
Elsewhere you configured `@react-native-community/geolocation` to `skipPermissionRequests` on the assumption that we will handle that... so there's no real reason to do this unless you really want to change `locationPermissionResult` to a new string object every single time we get a new a new location. I think we can just set the default value of `locationPermissionResult` to "granted" and only change it in the failure callback.

2024-07-12 10:39 UTC, jtklein commented
Changes to permissions PR #1594 are now merged in.
I did update the way useCurrentObservation is using location permission. Instead of checking for permission every time in the useEffect I added the `hasPermissions` state in as a hook param. I was not sure if `useUserLocation` and `fetchUserLocation` should check for permission every time they run or if the state kept in the functional component that make use of them is enough, and felt changing it is out of scope for my PR.
So, what I can see in the `useWatchPosition` hook here, you can decide if it is enough to know wether the rendered component has location permission or if the hook should check every time.

2024-07-16 16:23 UTC, merged