AI camera e2e test
inaturalist/iNaturalistReactNative pull request #2188
Opened 2024-09-25 21:22 UTC by jtklein

Closes #1981

2024-10-01 21:21 UTC, jtklein commented
Testing out the GitHub copilot feature of PR summary:
This pull request includes several changes to enhance the functionality and testing of the camera-related components in the project. The most important changes include improvements to the e2e test setup, updates to the `react-native-vision-camera` integration, and modifications to the `CameraRoll` mock. 

### E2E Testing Enhancements:
* Added comprehensive e2e test for the `AICamera` component, including user interactions and UI checks. (`e2e/aiCamera.e2e.js`)
* Updated `iNatE2eBeforeAll` and `iNatE2eBeforeEach` functions to include additional permissions for camera, media library, and photos. (`e2e/helpers.js`) [[1]](diffhunk://#diff-cab96705690a4dbe516eecc6326ee616109465b527b9fce3da9cd50d92678e68L7-R12) [[2]](diffhunk://#diff-cab96705690a4dbe516eecc6326ee616109465b527b9fce3da9cd50d92678e68L20-R30)

### Camera Integration Updates:
* Wrapped `react-native-vision-camera` components and methods in a custom wrapper to facilitate mocking for e2e tests. (`src/components/Camera/helpers/visionCameraWrapper.js`, `src/components/Camera/helpers/visionCameraWrapper.e2e-mock.js`) [[1]](diffhunk://#diff-b7fc60f61d6ff24a15c83dd1cbfd9fa7e309464bac016f9b487f7b81b9874df4R1-R12) [[2]](diffhunk://#diff-3f4432eb59d5a8482e95c6b7f23a9b76ed1e712436eae3852219bf7dada2cefdR1-R20)
* Replaced direct imports of `react-native-vision-camera` with the custom wrapper in various camera-related components. (`src/components/Camera/AICamera/FrameProcessorCamera.js`, `src/components/Camera/CameraContainer.tsx`, `src/components/Camera/CameraView.tsx`, `src/components/Camera/CameraWithDevice.tsx`, `src/components/Camera/hooks/useFocusTap.ts`, `src/components/Camera/hooks/useTakePhoto.ts`) [[1]](diffhunk://#diff-8a2655d811c511b40ffd6859d0ff5a3beeb7a92dbee51a37bf60aba971603b3bR4-L20) [[2]](diffhunk://#diff-0933ef94fea1853260eb95c4c953a804d29c6b2a01a3fce3ab39ca03363f37b8R2-L8) [[3]](diffhunk://#diff-f95e5a67d81693298a7050469dce0708281034c71594e21faa5b0d9f629bffb9R3-R6) [[4]](diffhunk://#diff-40620d275cd70938b335b606600b3b669d0033d17ba2056d8496a0335e181d7eR2) [[5]](diffhunk://#diff-5d1c67c1603eb775196d565d67695e39ecc2ac6af53e609f38b6cf37daea7662R1) [[6]](diffhunk://#diff-abd53b5316a9abc275006053cece6cd863c2d5a8c725ece1dc08a703604b4ae5R1-R7)

### Mock Improvements:
* Modified the `CameraRoll` mock to return a promise that resolves with a sample photo structure. (`__mocks__/@react-native-camera-roll/camera-roll.ts`)
* Added `copyAssetsFileIOS` method to the `react-native-fs` mock. (`__mocks__/react-native-fs.ts`)

### Dependency Updates:
* Updated the `detox` dependency to the latest version. (`package.json`)

### Code Cleanup:
* Converted several imports to use `type` imports for better type safety and clarity. (`src/components/Camera/AICamera/AICameraButtons.tsx`, `src/components/Camera/Buttons/Flash.tsx`, `src/components/Camera/TabletButtons.tsx`) [[1]](diffhunk://#diff-02a87331c07e84a384b941374a7a7e484b8fdf99cb89e101cf93260e9343e730L12-R12) [[2]](diffhunk://#diff-cf48ce06f7c3561f734d9397210b9bb35b15bc53192b219940c4aeab8c99d680L8-R8) [[3]](diffhunk://#diff-2c70875a40e441ecb6c8bd0e69926daed5e432e3896aedbc421bd8f49df8ad3aL9-R9)

These changes collectively improve the robustness of the camera functionality and the reliability of the e2e tests.

2024-10-23 09:11 UTC, jtklein commented on src/components/Camera/AICamera/FrameProcessorCamera.js
> +  const [lastTimestamp, setLastTimestamp] = useState( undefined );
See below

2024-10-23 09:14 UTC, jtklein commented on src/components/Camera/AICamera/FrameProcessorCamera.js
> +      if ( lastTimestamp ) {
This is a small bugfix, the first few frames - from init of screen to the first time the check becomes truthy - were not send to the camera. Now it starts immediately.

2024-10-23 09:40 UTC, jtklein commented on src/components/Camera/helpers/visionCameraWrapper.e2e-mock
> +import { useFrameProcessor } from "react-native-vision-camera";
Note that we are not mocking the useFrameProcessor hook. So, in the e2e test a real frame processor in the sense of react-native-vision-camera is built. As you can see in the next wrapper file our plugin is not used though in this frame processor and only a mocked prediction is immediately returned.

2024-10-23 09:50 UTC, jtklein commented on src/components/Camera/helpers/visionPluginWrapper.e2e-mock
> +  inatVision: mockVision
We are mocking the frame processor plugin to return a defined mocked prediction.

Note that we are not mocking the getPredictionsForImage function of the plugin, so in the e2e test when the mocked camera "saves" the photo and the app navigates to the suggestions screen. The real example cv model is run on the still image and the e2e test checks for a real prediction from the model .

2024-10-23 09:52 UTC, jtklein commented on src/components/ObsDetails/PhotoContainer.js
> -        loadSuccess !== null && "hidden"
This indicator's animation was always running in the background and keeping the e2e test from idling and proceeding to the next test step.

2024-10-24 12:54 UTC, jtklein commented on tests/vision-camera/vision-camera.js
> +        const testPhoto = r.edges[r.edges.length - 1].node.image;
Basically, we are reading the newest twenty photos from the simulators gallery and return the oldest one of those.

2024-10-24 12:59 UTC, jtklein commented on src/sharedHelpers/geolocationWrapper.e2e-mock
> +  if ( counter < 5 ) {
We have to limit this here to run only five times otherwise the e2e test never idles and times out.

2024-10-24 13:53 UTC, jtklein commented on e2e/aiCamera.e2e.js
> +    const deleteObservationButton = element( by.text( "DELETE" ) );
The e2e tests running from the cloud against production are actually uploading real photos so I am deleting it the observation immediately. From the iOS simulators the oldest photo found was always one of the preinstalled ones with a plant on it, so maybe good to monitor the test user from time to time if this deletion step is always succesfull or flaky.

2024-10-25 18:14 UTC, kueda requested changes
Interesting approach to mocking the camera and I'm glad it works. The main changes I want are

* Slim down / de-dupe / combine aiCamera.e2e.js; there's a lot of overlap with what's currently in signedin.e2e.js
* Move a lot of your very helpful comments in this PR to comments in the code; I think that will help everyone understand how this all works in the future

This doesn't need to block, but instead of using a photo from the camera roll, did you try using `require()` for a file in the repo, like we do for `require( "images/background/birger-strahl-ksiGE4hMiso-unsplash.jpg" )`? IMO using a file we create and control would be ideal.

2024-10-29 12:50 UTC, jtklein commented on src/components/ObsDetails/PhotoContainer.js
> -        loadSuccess !== null && "hidden"
I don't know if there is an advantage. It is much more common to find the `{renderFunction()}` approach in RN documentation and teaching materials.

2024-10-29 13:01 UTC, jtklein commented on e2e/aiCamera.e2e.js
> +  it( "should work", async () => {
Changed name

2024-10-30 10:53 UTC, jtklein commented on e2e/aiCamera.e2e.js
> +} );
Have now extracted some of the shared flows into separate files.

2024-10-30 10:54 UTC, jtklein commented on e2e/aiCamera.e2e.js
> +    await powerUserRadioButton.tap();
We don't need to. I could not figure out how to make the test pass when the element by id is found twice on the screen which it is in casual user mode.

2024-10-30 10:56 UTC, jtklein commented
Have extracted shared flows and added the comments into the code directly.

I have not tried with a require image. I don't know if the exif metadata part of the app will work if we present an image via a require call. We could try.

2024-11-01 17:35 UTC, kueda approved these changes

2024-11-01 17:38 UTC, merged