Fixes for ObsEdit & adding evidence to an existing observation
inaturalist/iNaturalistReactNative pull request #220
Opened 2022-11-04 00:44 UTC by albullington

Closes #217 and closes #218.

Basically, this is an attempt to clean up the whole uploader flow. I renamed `ObsEditProvider` to `UploadProvider` to make it clear that this includes state for all the uploader screens, including the camera, photo gallery, and group photos screen.

I moved a lot of the logic related to creating an observation, obs photo, and photo out of the models/components and into the `UploadProvider` so everything is in one place.

I also fixed the logic related to adding evidence to an existing observation. Now when you return to the Camera or PhotoGallery, you should only see the images which were previously selected/shown on that screen, and you should be able to add evidence in the expected format, without any duplicate obsPhotos being created.

One other change is that this pulls the timestamp, location, and place_guess from the gallery photos, which we weren't doing before. When there are observations with multiple photos, we're taking that data from the first photo in the list.

2022-11-05 01:00 UTC, kueda commented
Lots here so I'll dig into this next week. Off the top though, why UploadProvider? Most of these views don't have anything to do with uploading, i.e. sending data from the client to the server. IMO ObsEditProvider is a more descriptive name, but maybe I'm missing something.

2022-11-07 17:57 UTC, albullington commented
Upload made sense to me because internally we keep referring to all the screens within this provider as the uploader flow. Not attached to it though.

2022-11-07 23:38 UTC, kueda requested changes
I think I like putting logic in the provider... even if I don't always love the way context adds the risk of state overstaying its welcome.

Two things that we should touch base with Abhas about:

1. I support moving components into folders that match the names we're using the Figma doc, but I think the "BulkUploader" should be called the "PhotoImporter" because it doesn't upload anything.
2. I think ObsEditContext is a more descriptive name than "UploadContext" because it doesn't store context for any kind of upload process, whereas it does store context for editing (and adding) observations.

Only other things are the very minor stuff I mentioned in comments.

2022-11-07 23:38 UTC, kueda commented on src/providers/UploadProvider.js
> +  const createObservationsFromGroupedPhotos = useCallback( async obs => {
Can we stop using "obs" as an abbreviation? I always get confused about whether it means a single observation or multiple observations.

2022-11-07 23:38 UTC, kueda commented on src/providers/UploadProvider.js
> +    };
This method doesn't seem to get called. Can we delete it?

2022-11-08 20:08 UTC, kueda approved these changes

2022-11-08 20:16 UTC, merged