fix: add debounce to navigate function
inaturalist/iNaturalistReactNative pull request #2216
Opened 2024-10-02 14:26 UTC by israr002

closes #2204

2024-10-16 00:23 UTC, kueda requested changes
IMO this just makes things marginally more confusing to read without actually fixing the problem. Instead, check out https://github.com/react-navigation/react-navigation/issues/271#issuecomment-362726430. That's the solution recommended by the maintainers of react-naviation. Our situation is a little more complicated because we really do want to use `push()` and that doesn't seem to support extra stuff like the `key` param, but I think there's a way to do it with `navigate({ screen: "foo", key: "bar" })` if we construct our keys so that that they are always unique within the context of a single list of observations.

What we want is for something like this to open all new screens, no navigating back:

1. Go to MyObs
2. Tap on an observation
3. Tap on the observer's user icon to get to UserProfile
4. Tap on the observations stat to get to Explore
5. Tap on the same observation from step 2
6. A new instance of ObsDetails should be pushed onto the stack, you should *not* navigate back to the same ObsDetails instance from step 2

2024-10-16 00:23 UTC, kueda commented on src/components/ObservationsFlashList/MyObservationsPressable.js
> +  }, 200 );
This reduces the problem but does not remove it. I can still tap quickly and get two instances of ObsDetails pushed onto the stack.

2024-10-16 00:23 UTC, kueda commented on tests/integration/PhotoDeletion.test.js
> +    const addEvidenceButton = await waitFor( () => screen.findByLabelText( "Add evidence" ) );
I think all of the findBy* helpers basically do `waitFor` internally, so this should not be necessary, especially if you're not manually specifying a timeout.

2024-10-18 17:14 UTC, israr002 commented
@keuda I have done the required changes Please review.

2024-10-22 22:28 UTC, kueda requested changes
I can still reproduce the bug described in #2204 with these changes. I end up with keys like this:

`Obs-ObsList-wzflxz7sg-6FR9VWZxy6z-61152031-becd-4702-b281-ace2f4e936b5`
`Obs-Obs-ObsList-wzflxz7sg-6FR9VWZxy6z-61152031-becd-4702-b281-ace2f4e936b5-61152031-becd-4702-b281-ace2f4e936b5`

because `getCurrentRoute()` isn't telling you the route at the time the tap occurred, it's telling you the current route when `navigateToObservation()` gets called, which might actually be when you've already navigated to ObsDetails, resulting in that nested key.

To address this, I think you need to pass a prop down from every unique observation list, i.e. from MyObs, from every unique instance of Explore, etc. LMK if that doesn't make sense and I can take this one b/c I think I know how I would address this.

2024-10-28 22:53 UTC, closed without merging