Fix obs detail comment input
inaturalist/iNaturalistReactNative pull request #228
Opened 2022-11-04 23:24 UTC by albullington

Closes #213. Fixes the input issue by using `defaultValue` instead of `value`, since `value` was pulling the text input field from state instead of letting TextInput handle its own text state.

Also moves `AddCommentModal` into a separate component, updates styling for react-native components to use Tailwind, and creates a standardized backdrop component which we can use for all bottom sheet modals.

2022-11-05 01:24 UTC, kueda requested changes
Mostly looking good, but for some reason "Add optional notes" on ObsEdit now pushes the input way up above the keyboard when you enter it. Seems like it might be related to these changes.

2022-11-05 01:24 UTC, kueda commented on src/components/ObsDetails/AddCommentModal.js
> +      console.log( comment, "comment in add comment modal" );
Probably don't need this. Need to a way to lint console.log but not console.error...

2022-11-05 01:24 UTC, kueda commented on src/components/ObsDetails/AddCommentModal.js
> +      style={[viewStyles.commentInput, viewStyles.commentInputText, textStyles.commentTextInput]}
No way to do this with Tailwind?

2022-11-08 00:02 UTC, kueda requested changes
Now on my Pixel 3 there's a transparent gap between the soft keyboard and the input:

![Screenshot_20221107-155203](https://user-images.githubusercontent.com/22691/200440732-0a163b77-8211-4eab-895b-1142fa424684.jpg)


and on my iPad the soft keyboard covers the input entirely:

![IMG_0042](https://user-images.githubusercontent.com/22691/200441340-2e55d5fe-7392-4931-9b54-478335abd5b0.PNG)

2022-11-08 00:07 UTC, albullington commented
I couldn't figure out how to use Tailwind to position an element above the keyboard -- any suggestions?

2022-11-08 01:48 UTC, kueda commented
@albullington I haven't quite figured it out myself yet, but a few thoughts:

1. You can set an arbitrary height with Tailwind like this: `bottom-[${keyboardOffset}px]`
2. I suspect the problem might stem from actually restyling the same element when the keyboard appears. When I use `bottom-[${keyboardOffset}px]` it pushes the keyboard really high... like it was ${keyboardOffset}px and not ${keyboardOffset}px from the bottom of the screen. So I'm wondering if the solution might be to render one component for displaying the text, but another for editing it, and the editable one only appears when the user taps the display text. The editable component would always have absolute positioning, so in theory there's no possility of changing the baseline for `bottom`.

2022-11-09 00:22 UTC, albullington commented
This seems to be happening in the main branch too and wasn't something I could figure out in the past 24 hours, so I made a [separate issue](https://github.com/inaturalist/iNaturalistReactNative/issues/239).

2022-11-09 00:52 UTC, merged