Fixes for Map in Android
inaturalist/iNaturalistReactNative pull request #2594
Opened 2024-12-29 20:33 UTC by joergmlpts

+ The map from ObsDetails does not reset after each zoom anymore. A state for the region needed to be introduced and updated after each gesture.
+ The current location button now centers the map on the current location. A callback needed to be called explicitly after `animateToRegion()`.
+ A search in LocationPicker now centers the map on the selected location.  A state for the region needed to be introduced and a callback needed to be called explicitly after `animateToRegion()`.

Closes #2529
Closes #2555
Closes #2593

2025-01-06 20:07 UTC, kueda requested changes
This fixes all three bugs, which is great, but there are a lot of Android-specific carve-outs in this code that I suspect are going to cause confusion in the future. I want to be sure these changes cause problems in iOS and thus merit separate behavior, and if so, that we use names to reflect the OS-specific usage of these new variables.

2025-01-06 20:07 UTC, kueda commented on src/components/SharedComponents/Map/Map.tsx
> +  const [onMapReadyHasFired, setOnMapReadyHasFired] = useState( false );
Same here. This will be very confusing if for some reason we need to know if `onMapReady` has fired in iOS. The reader's assumption should be that it has if `onMapReadyHasFired` is true given the name, but it will be false. As above, I'd prefer this OS-specific functionality to be in a separate file, but failing that I think `onMapReadyHasFiredAndroid` or something would be more explicit.

2025-01-06 20:07 UTC, kueda commented on src/components/SharedComponents/Map/Map.tsx
> +  // In Android, we always return a state, either region or localRegion.
Does it cause a problem to always return a state in iOS? Why do we need OS-specific logic here?

2025-01-07 02:06 UTC, joergmlpts commented on src/components/SharedComponents/Map/Map.tsx
> +  // In Android, we always return a state, either region or localRegion.
I cannot build and test for iOS. So I kept the iOS functionality exactly the same.

Whether these states work for iOS is not clear. For example, on Android, `onMapReady` only fires when `initialRegion` is passed. A new state ensures that it will now fire in Android where we pass `region` instead of `initialRegion`. In iOS, if `onMapReady` also only fires when `initialRegion` is passed, iOS will not work with this code: The functionality that emulates `onMapReady` in Android is in a callback that is called when no gesture is detected. However, iOS only calls the callback when a gesture is detected.

2025-01-07 20:04 UTC, merged