270 ensure button is visible above keyboard on log in
inaturalist/iNaturalistReactNative pull request #275
Opened 2022-12-08 03:06 UTC by angielt

2022-12-10 00:22 UTC, kueda requested changes
This isn't showing the button above the keyboard for me on my Pixel 3 or in an iPhone 13 simulator. Assuming it's working for you, can you post a screenshot of what you're seeing?

2022-12-12 01:57 UTC, angielt commented
This PR makes the form scrollable so the button is accessible if you scroll up without clicking out of the keyboard but yes the button still requires a scroll to be seen even when you reach the password input box. I'm currently making changes. Is the 2nd video closer to the behavior we want? 

Current PR:
https://user-images.githubusercontent.com/13282161/206944051-6484c3c8-ff5c-4cd8-86b3-48e453a6242a.mp4


Making changes:
https://user-images.githubusercontent.com/13282161/206943626-75a7f944-b3fd-47e6-b896-7f8aa249381e.mp4

2022-12-14 01:01 UTC, kueda requested changes
Only blocking problem is the fact that the X button no longer works.

2022-12-14 01:01 UTC, kueda commented on src/components/LoginSignUp/Login.js
> +        onFocus={() => setExtraScrollHeight( 200 )}
I don't love this hardcoding, but I'm failing to find a better alternative so it works for now.

2022-12-16 20:22 UTC, merged