437 date display component
inaturalist/iNaturalistReactNative pull request #445
Opened 2023-02-07 01:15 UTC by Chrischuck

#437

2023-02-07 23:44 UTC, kueda requested changes
Looking good, only minor changes needed. Date formatting needs to be handled a little differently but that wasn't in the issue so I punted that to #448. FWIW, I'm also getting some `Warning: An update to DateDisplay inside a test was not wrapped in act(...).` errors when running tests, though I'm not 100% sure why. Would be nice to fix that, but I don't think it needs to block.

2023-02-07 23:44 UTC, kueda commented on package.json
> +    "test": "TZ=UTC jest",
Cool, didn't know you could do this.

2023-02-07 23:44 UTC, kueda commented on src/components/SharedComponents/DateDisplay.js
> +  console.log( displayTime() );
Please remove.

2023-02-08 01:37 UTC, Chrischuck commented
@kueda Looks like it has to do with the `useTranslation` hook. After removing it and running tests it seems to disappear. I can take a look into it as another issue.

2023-02-08 01:54 UTC, kueda approved these changes

2023-02-08 01:54 UTC, merged