489 contribution md
inaturalist/iNaturalistReactNative pull request #498
Opened 2023-02-22 12:00 UTC by jtklein

Adds a CONTRIBUTING.md file that should act as an exhaustive primer for developers that want to contribute to the project.

2023-02-25 01:16 UTC, kueda requested changes
Looks good! Mostly minor typos and requests. Happy to chat about them in Slack next week if that's easier.

2023-02-25 01:16 UTC, kueda commented on CONTRIBUTING.md
> +- Please make sure your code is well-documented, follows our code style guide, and includes unit tests.
We don't really have any documentation standards, so I'm not sure that's fair request. In terms of style, shouldn't our CI catch violations of our eslint rules?

2023-02-27 08:50 UTC, jtklein commented on CONTRIBUTING.md
> +If you find an issue or bug in our application, please report it by opening a new issue in the repository. Please include a clear and detailed description of the issue, steps to reproduce the issue,
Yes, I thought as long as the app is not available publicly it will be only on GitHub.

2023-03-21 17:22 UTC, kueda approved these changes

2023-03-21 17:22 UTC, merged