Create tab navigator
inaturalist/iNaturalistReactNative pull request #507
Opened 2023-02-25 13:16 UTC by Chrischuck

#499

2023-02-25 20:55 UTC, Chrischuck commented on src/components/ObsDetails/ObsDetails.js
> +      headerLeft: backButton
I'm not sure how this page had a back button w/o this code previously. But for what it's worth, I think that this should be defined w/ the screen definition in the navigator.

2023-03-09 12:16 UTC, jtklein requested changes
Hi @Chrischuck, have now managed to look through all of this PR. For the most part it looks good to me. Some issues I have seen in the apps:

On Android the back button is not visible, you can tap it though. I haven't checked if it is transparent or same color as the background, or a text with no string or ...

There is no more back button in the Taxon details screen.

Now that the footer is no longer there, these two pairs of components can be combined and renamed, as they are identical now:
ScrollNoFooter & ScrollWithFooter
ViewNoFooter & ViewWithFooter

2023-03-09 12:16 UTC, jtklein commented on src/realmModels/User.js
> +  static firstSignedInUser = realmObjects => realmObjects.filtered( "signedIn == true" )[0]
This deos not seem to be used somewhere.

2023-03-10 02:04 UTC, Chrischuck commented on src/components/ObsDetails/ObsDetails.js
> +      headerLeft: backButton
Can do, for future reference, in a Stack navigator, the back button gets automatically added if it is possible to go back. But when we switched to tab navigation, the behavior did not follow

2023-03-10 13:57 UTC, merged