655 accuracy circle and obscuration cell for obsdetail map
inaturalist/iNaturalistReactNative pull request #744
Opened 2023-08-23 00:29 UTC by angielt

- Accuracy Circle and Obscuration Cell
- Details Tab Map Screen 

Notes:
- Dashed lines for accuracy circle and obscuration cell omitted since it's only available on iOS according to docs for react-native-maps(https://github.com/react-native-maps/react-native-maps/blob/master/docs/circle.md). 
- Waiting on designs for obscuration based on me vs taxon geoprivacy

2023-09-07 20:43 UTC, kueda requested changes
This is a partial review, but I'm guessing it's plenty to work on.

- [ ] You changed the database schema so you need to bump the schema version in src/realmModels/index.js, otherwise the app won't start if it has an existing database with a prior schema
- [ ] The map on the DETAILS tab of ObsDetails doesn't show any of the obscuration cell, positional accuracy circle, etc.
- [ ] https://www.inaturalist.org/observations/159598562 should have an obscuration cell, but instead I see a stemmed map marker and accuracy circle at the position of the *obscured* coordinates

2023-09-14 01:30 UTC, kueda requested changes
Another round of feedback! Holler if you have any questions. Here are some that didn't fit inline:

- [x] Copy Coordinates button closes DetailsMap when the toast fades away
- [x] Missing [geoprivacy indicator](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=1493-12165&mode=design&t=hjZ2bF9xKLohwFyA-4) below the map on ObsDetail

2023-09-14 01:30 UTC, kueda commented on src/realmModels/index.js
> +  schemaVersion: 42,
Why 42 and not 40?

2023-09-14 04:51 UTC, angielt commented on src/components/SharedComponents/Map.js
> +  const obscuredCoordinates = useMemo( () => returnRandomArbitraryCoordinates(), [] );
Really? I didn't realize that they were. I'll remove this then.

2023-09-15 19:39 UTC, kueda commented on src/components/SharedComponents/Map.js
> +  const obscuredCoordinates = useMemo( () => returnRandomArbitraryCoordinates(), [] );
Yeah, the server decides what the client has access to. The client's responsibility is to *display* the location properly (e.g. with an obscuration cell or with an accuracy circle), but the client doesn't need to actually perform the obscuration itself.

2023-09-19 21:00 UTC, kueda requested changes
Getting closer! Here are a few more in addition to the inline feedback:

- [ ] The map marker is using the obscured coordinates even when the private coordinates are available. The map should show `privateLatitude` and `privateLongitude` if they are available. The symptom I'm seeing is that when I look at an observation of mine where geoprivacy is `obscured`, the map marker looks unobscured (stemmed map marker), but the location is wrong (should be in my back yard, is in another town instead).
- [ ] When I tap the share button on the DetailsMap, it opens Apple Maps on iOS and Google Maps on Android, but I don't see a map marker on either. Is that expected?
- [ ] Resolve conflicts with main

2023-09-20 00:11 UTC, angielt commented on src/components/SharedComponents/ObservationLocation.js
> +    if ( obscured ) {
I see. So coordinates obscured takes into account the taxon geoprivacy. For several of my observations and []((https://www.inaturalist.org/observations/159598562)) i'm seeing geoprivacy as null.  A bit confused on what to do in this case.

2023-09-20 16:44 UTC, kueda commented on src/components/SharedComponents/ObservationLocation.js
> +    if ( obscured ) {
`observation.geopricacy == null` should be treated the same as `observation.geoprivacy == "open"`.

2023-10-07 02:27 UTC, kueda approved these changes

2023-10-09 19:41 UTC, merged